services:
  api:
    build: ./app_API
    ports:
      - "8000:8000"
    networks:
      - my_network

  streamlit:
    build: ./app_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - my_network

networks:
  my_network:
    driver: bridge